### ISSUE TITLE
Connect server to Ionic app

### ISSUE THREAD

**Issue by bjsawyer** [excellalabs/excella-central#26]
Using the excella-central-server (and info that Kevin sent in the Slack channel), we need to hook up the GraphQL/Loopback API to our Ionic app so we can start using real data.

**Comment by bjsawyer** [comment]
@alexhoffman617 I know you mentioned that Kevin had given you some info on this. Do you think this is something we can get working soon? I'd be glad to help but don't know the first thing about the server or GraphQL.

**Comment by bjsawyer** [comment]
[Apollo for Angular](http://dev.apollodata.com/angular2/initialization.html)

**Comment by alexhoffman617** [comment]
Below is a simple http version of the query we can use for the time being as we make a decision on what to do with graphql

https://central.excellalabs.com/graphql?query=query{allProfiles{profiles:profiles{firstName,lastName,avatarUrl,primarySkill,client,funFact,id}}}

**Comment by bjsawyer** [comment]
@gardinerhugh6 got some API routing hooked up in #29. So now we can see the actual API results rendering in the Directory page, and next we can work on the Apollo GraphQL integration for Angular (for querying).
